---
# tasks file for ffmpeg-cuda

# apt
- name: Update APT package cache
  apt: update_cache=yes
  tags: apt

- name: Install packages
  apt: >
    name={{ deps }} state=latest
  tags: apt

# git
- name: clone latest yasm
  git: repo={{ repo_yasm }}
       dest={{ source_dir }}/yasm 
       accept_hostkey=yes

- name: clone latest ffmpeg
  git: repo={{ repo_ffmpeg }}
       dest={{ source_dir }}/ffmpeg
       accept_hostkey=yes

- name: clone latest nv_codec
  git: repo={{ repo_nv_codec }}
       dest={{ source_dir }}/nv_codec
       accept_hostkey=yes

# Compiling
- name: compile yasm 
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/yasm" 
    creates: "{{ bin_dir }}/yasm"
  with_items:
    - ./autogen.sh
    - ./configure --bindir={{ bin_dir }}
    - make
    - make install
    - make distclean

- name: compile nv_codec
  command: "{{ item }}" 
  args:
    chdir: "{{ source_dir }}/nv_codec" 
  with_items:
    - make
    - make install

- name: copy file cudash in profile.d and setting path
  copy: src=../files/cuda.sh dest=/etc/profile.d/cuda.sh

- name: ldconfig cuda for nvcc
  copy: src=../files/cuda.conf dest=/etc/ld.so.conf.d/cuda.conf

- name: ldconfig
  command: /sbin/ldconfig

- name: compile ffmpeg
  command: "{{ item }}" 
  args:
    chdir: "{{ source_dir }}/ffmpeg"
  with_items:
    - ./configure --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-libopencv --disable-outdev=sdl2 --disable-podpages --disable-sndio --disable-stripping --enable-libaom --enable-avfilter --enable-avresample --enable-gcrypt --disable-gnutls --enable-openssl --enable-gpl --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmp3lame --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libzimg --enable-libxvid --enable-libzvbi --enable-nonfree --enable-opencl --enable-opengl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-libwebp --enable-libx264 --enable-libdc1394 --enable-vaapi --enable-libmfx --enable-libvmaf --disable-altivec --enable-nvenc --enable-cuda --enable-cuvid --enable-cuda-nvcc --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
    - make
    - make install
    - make distclean
