---
# tasks file for ffmpeg-cuda

# apt
- name: Update APT package cache
  apt: update_cache=yes
  tags: apt

- name: Install packages
  apt: >
    name={{ deps }} state=latest
  tags: apt

# git
- name: clone latest yasm
  git: repo={{ repo_yasm }}
       dest={{ source_dir }}/yasm 
       accept_hostkey=yes

- name: clone latest ffmpeg
  git: repo={{ repo_ffmpeg }}
       dest={{ source_dir }}/ffmpeg
       accept_hostkey=yes

- name: clone latest nv_codec
  git: repo={{ repo_nv_codec }}
       dest={{ source_dir }}/nv_codec
       accept_hostkey=yes

# Compiling
- name: compile yasm 
  command: "{{ item }}"
  args:
    chdir: "{{ source_dir }}/yasm" 
    creates: "{{ bin_dir }}/yasm"
  with_items:
    - ./autogen.sh
    - ./configure --bindir={{ bin_dir }}
    - make
    - make install
    - make distclean

- name: compile nv_codec
  command: "{{ item }}" 
  args:
    chdir: "{{ source_dir }}/nv_codec" 
  with_items:
    - make
    - make install

- name: copy file cudash in profile.d and setting path
  copy: src=../files/cuda.sh dest=/etc/profile.d/cuda.sh

- name: ldconfig cuda for nvcc
  copy: src=../files/cuda.conf dest=/etc/ld.so.conf.d/cuda.conf

- name: ldconfig
  command: /sbin/ldconfig

- name: compile ffmpeg
  shell: |
    set -e
    ./etc/profile.d/cuda.sh
    ./configure {{ ffmpeg_compile_options }}
    make -j$(nproc)
    make install
    make distclean
  args:
    chdir: "{{ source_dir }}/ffmpeg"
